spring:
  application:
    name: flight-service
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  api:
    host:
      customersUrl: http://localhost:8201/customers
      flightsUrl: http://localhost:8202/flights

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

server:
  port: 8203
  error:
    include-message: always